### ISSUE TITLE
Misssing file for Magento 2.2.x Class Gracious\Interconnect\Observer\CheckoutCartProductAddAfter does not exist

### ISSUE THREAD

**Issue by martijn-bigbridge** [graciousstudios/interconnect-magento2#11]
Hi,

After upgrading to Magento 2.2.4 we get this exception:

Exception #0 (ReflectionException): Class Gracious\Interconnect\Observer\CheckoutCartProductAddAfter does not exist

Is it possible that you create this (dummy) file:
Or disable it inside:

vendor/graciousstudios/interconnect-magento2/etc/events.xml

    

Thanks.

**Comment by michaelgracious** [comment]
placeholder class is zit er nu bij

**Comment by martijn-bigbridge** [comment]
Oke, bedankt.

Zou je nog een fout kunnen oplossen, dan klopt het.

Exception #0 (LogicException): Observer "Gracious\Interconnect\Observer\CheckoutCartProductAddAfter" must implement interface "Magento\Framework\Event\ObserverInterface"

Met de onderstaande code zou het wel werken.

```<?php

namespace Gracious\Interconnect\Observer;

use Magento\Framework\Event\Observer as EventObserver;

class CheckoutCartProductAddAfter extends Observer
{

    /**
     * @param Observer $observer
     * @return void
     */
    public function execute(EventObserver $observer)
    {
        return;
    }
}
```

**Comment by michaelgracious** [comment]
Fixed
